default:
  # use fuzzy match by default
  mode: fuzzy
  fuzzy:
    thres: 90
  case-sensitive: false

label-nonmatch: ambigous

rules:
  # --- usage ---
  usage_compile:
    match:
      - keyword: make emu
      - keyword: make verilog
      - keyword: compile
    label: "usage: compile"
    # finalize here, no need to check following rules
    final: true

  usage_simulate:
    match:
      - keyword: vcs
      - keyword: simulate
    label: "usage: sim"
    final: true



  # --- frontend ---
  module_frontend_bpu:
    match:
      # use regex to match the short keyword
      - keyword: BPU
        mode: regex
      - keyword: (IT)?TAGE
        mode: regex
        # use case-sensitive match to prevent false positive like "stage" from being matched
        case-sensitive: true
      - keyword: Branch Prediction
    label: "module: frontend-BPU"
    assignees:
      - ngc7331

  module_frontend_ifu:
    match:
      - keyword: IFU
        mode: regex
      - keyword: Instruction Fetch Unit
    label: "module: frontend-IFU"
    assignees:
      - ngc7331-bot

  module_frontend_ftq:
    match:
      - keyword: FTQ
        mode: regex
      - keyword: Fetch Target Queue
    label: "module: frontend-FTQ"

  module_frontend_icache:
    match:
      - keyword: ICache
        mode: regex
      - keyword: Instruction Cache
    label: "module: frontend-ICache"

  module_frontend_general:
    match:
      - keyword: frontend
    label: "module: frontend"
    skip-if:
      - module_frontend_bpu
      - module_frontend_ifu
      - module_frontend_ftq
      - module_frontend_icache



  # --- backend ---
  module_backend_dispatch:
    match:
      - keyword: Dispatch
    label: "module: backend-Dispatch"

  module_backend_general:
    match:
      - keyword: backend
    label: "module: backend"
    skip-if:
      - module_backend_dispatch



  # --- memory ---
  module_memory_lsq:
    match:
      - keyword: LSQ
        mode: regex
      - keyword: Load Store Queue
    label: "module: memory-LSQ"

  module_memory_general:
    match:
      - keyword: memory
    label: "module: memory"
    skip-if:
      - module_memory_lsq



  # --- cache ---
  module_cache_general:
    match:
      - keyword: cache
    label: "module: cache"
    skip-if:
      - module_frontend_icache



  # --- others ---
  module_difftest:
    match:
      - keyword: difftest
    label: "module: difftest"

  module_nemu:
    match:
      - keyword: nemu
    label: "module: nemu"
