name: issue-labeler
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: ngc7331/actions-issue-labeler@v0.0.1
      with:
        BOT_GITHUB_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
        CONFIG_PATH: .github/issue-labeler.yml
