name: issue-labeler
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: zzyyyl/issue-checker@v1.7
      with:
        repo-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
        configuration-path: .github/issue-labeler.yml
        include-title: 1
        sync-labels: 1
